module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "apponon-white": "var(--apponon-white)",
        "apponon-white-action": "var(--apponon-white-action)",
        appwhite: "var(--appwhite)",
        "component-informationdefault": "var(--component-informationdefault)",
        "component-lightdefault": "var(--component-lightdefault)",
        componentcustombackgroundbackgrounddefault:
          "var(--componentcustombackgroundbackgrounddefault)",
        componentdarkbackground: "var(--componentdarkbackground)",
        componentdarkdefault: "var(--componentdarkdefault)",
        componentghostdefault: "var(--componentghostdefault)",
        componentlightbackground: "var(--componentlightbackground)",
        componentlightdesc: "var(--componentlightdesc)",
        componentlightlabel: "var(--componentlightlabel)",
        componentlightoutline: "var(--componentlightoutline)",
        componentlightoutlineclickable: "var(--componentlightoutlineclickable)",
        componentlightplaceholder: "var(--componentlightplaceholder)",
        "componentonon-primary": "var(--componentonon-primary)",
        componentprimary: "var(--componentprimary)",
        componentprimarybackground: "var(--componentprimarybackground)",
        componentsecondarybackground: "var(--componentsecondarybackground)",
        componentstatusbackgroundinformation:
          "var(--componentstatusbackgroundinformation)",
        componentstatusdefault: "var(--componentstatusdefault)",
        "page-darkdefault": "var(--page-darkdefault)",
        "page-lightbackground": "var(--page-lightbackground)",
        pagedarkbackground: "var(--pagedarkbackground)",
        pagedarkcomponentghostactive: "var(--pagedarkcomponentghostactive)",
        pagedarkcomponentghostbackground:
          "var(--pagedarkcomponentghostbackground)",
        pagedarkcomponentghostdefault: "var(--pagedarkcomponentghostdefault)",
        pagelightsuccess: "var(--pagelightsuccess)",
        pagelighttextdefault: "var(--pagelighttextdefault)",
        primaryconfidentblue: "var(--primaryconfidentblue)",
        primaryhonestwhite: "var(--primaryhonestwhite)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "default-bold-body": "var(--default-bold-body-font-family)",
        "TTB-allcap": "var(--TTB-allcap-font-family)",
        "ttb-button-big": "var(--ttb-button-big-font-family)",
        "TTB-buttonsmall": "var(--TTB-buttonsmall-font-family)",
        "TTB-h3": "var(--TTB-h3-font-family)",
        "TTB-labelinput": "var(--TTB-labelinput-font-family)",
        "TTB-labellist": "var(--TTB-labellist-font-family)",
        "TTB-labelxsmall": "var(--TTB-labelxsmall-font-family)",
        "TTB-pagetitle": "var(--TTB-pagetitle-font-family)",
        "TTB-paragraphmedium": "var(--TTB-paragraphmedium-font-family)",
        "TTB-paragraphsmall": "var(--TTB-paragraphsmall-font-family)",
        "TTB-paragraphxsmall": "var(--TTB-paragraphxsmall-font-family)",
        "TTB-subtitle": "var(--TTB-subtitle-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "down-shadow": "var(--down-shadow)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
